### PR TITLE
fix(type-safe-api): add empty README.md for generated python projects

### LINKED ISSUE #813: [BUG] (type-safe-api) install fails on python runtime package with missing README
### Describe the bug

After cloning a project repo and installing the monorepo's dependencies with `pnpm install` or similar, packages that depend on an API's python runtime package fail because the generated README.md is missing and `poetry install` requires it. Using `commitGenerated` in the type safe api package or the python runtime options still includes the README.md and the module files in the runtime's .gitignore.

### Expected Behavior

After cloning a project repo, I should be able to install dependencies and build all packages.

### Current Behavior

After cloning the repo and running `pnpm i`:

> │ > nx run api-detective-api-python-handlers:install
> │ api-detective-api-python-handlers: Progress: resolved 1, reused 0, downloaded 0, added 0
> │ api-detective-api-python-handlers: Packages: +2
> │ api-detective-api-python-handlers: ++
> │ api-detective-api-python-handlers: Progress: resolved 2, reused 1, downloaded 0, added 1
> │ api-detective-api-python-handlers: Progress: resolved 2, reused 2, downloaded 0, added 1
> │ api-detective-api-python-handlers: Progress: resolved 2, reused 2, downloaded 0, added 2
> │ api-detective-api-python-handlers: Progress: resolved 2, reused 2, downloaded 0, added 2, done
> │ api-detective-api-python-handlers: 👾 install | poetry env use python$PYTHON_VERSION
> │ api-detective-api-python-handlers: Creating virtualenv api-detective-api-python-handlers-CBvV-DEk-py3.12 in /Users/strunkjd/Library/Caches/pypoetry/virtualenvs
> │ api-detective-api-python-handlers: Using virtualenv: /Users/strunkjd/Library/Caches/pypoetry/virtualenvs/api-detective-api-python-handlers-CBvV-DEk-py3.12
> │ api-detective-api-python-handlers: 👾 install | poetry update
> │ api-detective-api-python-handlers: Updating dependencies
> │ api-detective-api-python-handlers: Resolving dependencies...
> │ api-detective-api-python-handlers: Package operations: 79 installs, 0 updates, 0 removals
> │ api-detective-api-python-handlers:   - Installing ...
> ...
> │ api-detective-api-python-handlers:   - Installing api-detective-api-python-runtime (0.0.0 /private/tmp/api-detective/packages/api/generated/runtime/python)
> │ api-detective-api-python-handlers:   ChefBuildError
> │ api-detective-api-python-handlers:   Backend subprocess exited when trying to invoke build_editable
> │ api-detective-api-python-handlers:   
> │ api-detective-api-python-handlers:   Traceback (most recent call last):
> │ api-detective-api-python-handlers:     File "/Users/strunkjd/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
> │ api-detective-api-python-handlers:       main()
> │ api-detective-api-python-handlers:     File "/Users/strunkjd/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
> │ api-detective-api-python-handlers:       json_out["return_val"] = hook(**hook_input["kwargs"])
> │ api-detective-api-python-handlers:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:     File "/Users/strunkjd/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 294, in build_editable
> │ api-detective-api-python-handlers:       return hook(wheel_directory, config_settings, metadata_directory)
> │ api-detective-api-python-handlers:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:     File "/var/folders/4_/kvx9bwf15_j628lytjzz0mwc0000gq/T/tmp5cjmi4ri/.venv/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 82, in build_e…
> │ api-detective-api-python-handlers:       return WheelBuilder.make_in(
> │ api-detective-api-python-handlers:              ^^^^^^^^^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:     File "/var/folders/4_/kvx9bwf15_j628lytjzz0mwc0000gq/T/tmp5cjmi4ri/.venv/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 81,…
> │ api-detective-api-python-handlers:       wb = WheelBuilder(
> │ api-detective-api-python-handlers:            ^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:     File "/var/folders/4_/kvx9bwf15_j628lytjzz0mwc0000gq/T/tmp5cjmi4ri/.venv/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 62,…
> │ api-detective-api-python-handlers:       super().__init__(poetry, executable=executable)
> │ api-detective-api-python-handlers:     File "/var/folders/4_/kvx9bwf15_j628lytjzz0mwc0000gq/T/tmp5cjmi4ri/.venv/lib/python3.12/site-packages/poetry/core/masonry/builders/builder.py", line 5…
> │ api-detective-api-python-handlers:       self._meta = Metadata.from_package(self._package)
> │ api-detective-api-python-handlers:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:     File "/var/folders/4_/kvx9bwf15_j628lytjzz0mwc0000gq/T/tmp5cjmi4ri/.venv/lib/python3.12/site-packages/poetry/core/masonry/metadata.py", line 58, in fr…
> │ api-detective-api-python-handlers:       with readme.open(encoding="utf-8") as f:
> │ api-detective-api-python-handlers:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:     File "/Users/strunkjd/.pyenv/versions/3.12.2/lib/python3.12/pathlib.py", line 1013, in open
> │ api-detective-api-python-handlers:       return io.open(self, mode, buffering, encoding, errors, newline)
> │ api-detective-api-python-handlers:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> │ api-detective-api-python-handlers:   FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/api-detective/packages/api/generated/runtime/python/README.md'
> │ api-detective-api-python-handlers:   
> │ api-detective-api-python-handlers:   at ~/.pyenv/versions/3.12.2/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
> │ api-detective-api-python-handlers:       160│ 
> │ api-detective-api-python-handlers:       161│                 error = ChefBuildError("\n\n".join(message_parts))
> │ api-detective-api-python-handlers:       162│ 
> │ api-detective-api-python-handlers:       163│             if error is not None:
> │ api-detective-api-python-handlers:     → 164│                 raise error from None
> │ api-detective-api-python-handlers:       165│ 
> │ api-detective-api-python-handlers:       166│             return path
> │ api-detective-api-python-handlers:       167│ 
> │ api-detective-api-python-handlers:       168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
> │ api-detective-api-python-handlers: Note: This error originates from the build backend, and is likely not a problem with poetry but with api-detective-api-python-runtime (0.0.0 /private/tmp/…
> │ api-detective-api-python-handlers: 👾 Task "install" failed when executing "poetry update" (cwd: /private/tmp/api-detective/packages/api/handlers/python)
> │ api-detective-api-python-handlers: Warning: run-commands command "pnpm dlx projen install" exited with non-zero status code

### Reproduction Steps

 .projenrc.ts
``` ts
const pdkVersion = "0.23.40";
const projectName = "sample";

const project = new monorepo.MonorepoTsProject({
  devDeps: [`@aws/pdk@${pdkVersion}`],
  name: projectName,
  packageManager: javascript.NodePackageManager.PNPM,
  projenrcTs: true,
  gitignore: [".bashrc", ".profile", ".idea"],
  prettier: true,
});

const api = new TypeSafeApiProject({
  parent: project,
  name: `${projectName}-api`,
  outdir: "packages/api",
  model: {
    language: ModelLanguage.OPENAPI,
    options: {
      openapi: {
        title: `${projectName}-api`,
      },
    },
  },
  infrastructure: {
    language: Language.TYPESCRIPT,
  },
  handlers: {
    languages: [Language.PYTHON],
  },
  runtime: {
    languages: [Language.PYTHON],
    options: {
      python: {
          commitGenerated: true,
      },
    },
  },
  commitGenerated: true,
});
```

### Possible Solution

First, `commitGenerated: true` in a Python runtime package doesn't work. `.gitignore` still includes the README.md and module directory:

packages/api/generated/runtime/python/.gitignore
```
sample_api_python_runtime
README.md
```

Second, commitGenerated on the type safe api project should be recursively applied to child projects.

### Additional Information/Context

Mitigation:

After defining the api project in .projenrc.ts, add the following:
```
api.runtime.python?.gitignore.removePatterns(
  "README.md",
  api.runtime.python?.moduleName,
);
```

### PDK version used

0.23.40

### What languages are you seeing this issue on?

Typescript, Python

### Environment details (OS name and version, etc.)

MacOS 14.5 intel

### PR DESCRIPTION
**Pull request by jstrunk**
The poetry install that runs as part of post synthesis expects there to be some code present, but code isn't generated until build time. This means that the first install will fail when either generating the project for the first time or checking out a fresh copy (since generated code is not checked in to version control).

To fix this, we add a blank README.md file in addition to the __init__.py file as the first install step to keep poetry happy until the generator overwrites it.

Fixes #813

### CODE REVIEW

File: packages/type-safe-api/src/project/codegen/infrastructure/cdk/generated-python-cdk-infrastructure-base-project.ts [hunk 1]
```diff
@@ -120,13 +120,13 @@ export abstract class GeneratedPythonCdkInfrastructureBaseProject extends Python
...
-    // therefore add a blank __init__.py as our first install step to keep poetry happy until the generator overwrites
-    // it.
+    // therefore add a blank __init__.py and README.md as our first install step to keep poetry happy until the
+    // generator overwrites it.
     ["install", "install:ci"].forEach((t) =>
       this.tasks
         .tryFind(t)
         ?.prependExec(
-          `mkdir -p ${this.moduleName} && touch ${this.moduleName}/__init__.py`
+          `mkdir -p ${this.moduleName} && touch ${this.moduleName}/__init__.py README.md`
```
Comment (agdimech) [inline packages/type-safe-api/src/project/codegen/infrastructure/cdk/generated-python-cdk-infrastructure-base-project.ts:129]: Shouldn't this be `${this.moduleName}/README.md` ?

File: packages/type-safe-api/src/project/codegen/runtime/generated-python-runtime-base-project.ts [hunk 2]
```diff
@@ -113,13 +113,13 @@ export abstract class GeneratedPythonRuntimeBaseProject extends PythonProject {
...
-    // therefore add a blank __init__.py as our first install step to keep poetry happy until the generator overwrites
-    // it.
+    // therefore add a blank __init__.py and README.md as our first install step to keep poetry happy until the
+    // generator overwrites it.
     ["install", "install:ci"].forEach((t) =>
       this.tasks
         .tryFind(t)
         ?.prependExec(
-          `mkdir -p ${this.moduleName} && touch ${this.moduleName}/__init__.py`
+          `mkdir -p ${this.moduleName} && touch ${this.moduleName}/__init__.py README.md`
```
Comment (agdimech) [inline packages/type-safe-api/src/project/codegen/runtime/generated-python-runtime-base-project.ts:122]: Shouldn't this be `${this.moduleName}/README.md` ?

**Comment by jstrunk** [comment]
No. Poetry looks for a README.md at the same level as the pyproject.toml
which is the package root. The source code starts in the module directory,
so the __init__.py goes there.

File: packages/type-safe-api/src/project/codegen/infrastructure/cdk/generated-python-cdk-infrastructure-base-project.ts (hunk 1 above)
Comment (jstrunk) [reply packages/type-safe-api/src/project/codegen/infrastructure/cdk/generated-python-cdk-infrastructure-base-project.ts:129]: No. Poetry looks for a README.md at the same level as the pyproject.toml
which is the package root. The source code starts in the module directory,
so the __init__.py goes there.

File: packages/type-safe-api/src/project/codegen/runtime/generated-python-runtime-base-project.ts (hunk 2 above)
Comment (jstrunk) [reply packages/type-safe-api/src/project/codegen/runtime/generated-python-runtime-base-project.ts:122]: No. Poetry looks for a README.md at the same level as the pyproject.toml
which is the package root. The source code starts in the module directory,
so the __init__.py goes there.

**Comment by jstrunk** [comment]
```
% pwd
packages/api/generated/runtime/python
% ls -R
README.md				poetry.lock
api_detective_api_python_runtime	poetry.toml
dist					project.json
docs					pyproject.toml
openapitools.json

./api_detective_api_python_runtime:
__init__.py
...
```

**Review by agdimech — APPROVED** [review]
