### PR TITLE
fix(docs): fail docs build when errors are thrown

### LINKED ISSUE #57: [BUG] Doc build can still succeed even though there are partial failures
### Describe the bug

It is possible for the docs build to succeed with partial failures as per: https://github.com/aws/aws-prototyping-sdk/actions/runs/2539820405

### Expected Behavior

This should not be the case and the build should fail if any submodule fails to render docs.

### Current Behavior

docs build succeeds even though there are partial failures.

### Reproduction Steps

happens intermittently.

### Possible Solution

N/A

### Additional Information/Context

_No response_

### PDK version used

0.2.8

### What languages are you seeing this issue on?

Typescript, Java, Python

### Environment details (OS name and version, etc.)

github

### PR DESCRIPTION
**Pull request by agdimech**
This PR fails the build when any failures are detected in the markdown generator.

Additional fixes:
  - Perform synth on build/release workflows to ensure no mutable changes.
  - Cleanup old references to identity (this won't happen anymore with above fix).

Fixes #57

### CODE REVIEW

File: public/docs/scripts/generate-markdown.js [hunk 1]
```diff
@@ -62,14 +62,15 @@ async function main() {
...
+  const languages = SUPPORTED_LANGUAGES.map((l) => l.name);
+  for (const language of languages) {
     fs.mkdirSync(`${cwd}/build/docs/content/${language}`, { recursive: true });
 
     const pkgs = fs.readdirSync(RELATIVE_PKG_ROOT)
       .filter(p => "aws-prototyping-sdk" !== p)
       .filter(p => fs.existsSync(`${RELATIVE_PKG_ROOT}/${p}/.jsii`));
 
-    pkgs.map(async (pkg) => {
+    for (const pkg of pkgs) {
```
Comment (cogwirrel) [inline public/docs/scripts/generate-markdown.js:73]: Nice catch! :)

**Review by cogwirrel — APPROVED** [review]

File: public/docs/scripts/generate-markdown.js (hunk 1 above)
Comment (agdimech) [reply public/docs/scripts/generate-markdown.js:73]: Thanks.
