### PR TITLE
fix: resolve issue with license not being overriden

### LINKED ISSUE #784: [BUG] Upgrading core pdk code results in reverting back to the original versions.
### Describe the bug

Attempting to upgrade pdk, pdk dependencies and projen roles back to previous versions.

### Expected Behavior

aws/pdk should be upgraded to latest and projen should be upgraded to latest.

### Current Behavior

Relevant bits of the upgrade logs included from reproduction steps below.

1. `@aws/pdk` goes from `0.23.35` to `0.23.38` then back to `0.23.35`

```bash
> @demo/monorepo@0.0.0 upgrade UpgradeDemo
> pnpm exec projen upgrade

👾 upgrade | pnpm dlx npm-check-updates@16 --upgrade --target=minor --peer --dep=dev,peer,prod,optional --filter=eslint-config-prettier,eslint-import-resolver-typescript,eslint-plugin-import,eslint-plugin-prettier,npm-check-updates,prettier,ts-node,typescript,@aws-cdk/aws-cognito-identitypool-alpha,aws-cdk-lib,cdk-nag
Progress: removed
Using pnpm
Upgrading UpgradeDemo/package.json
[====================] 11/11 100%
[====================] 3/3 100%

 aws-cdk-lib         2.137.0  →   2.142.1
 cdk-nag             2.28.92  →  2.28.119
 npm-check-updates  16.14.18  →  16.14.20

Run pnpm install to install new versions.
👾 upgrade | pnpm i --no-frozen-lockfile
Scope: all 3 workspace projects
Progress: removed

dependencies:
- aws-cdk-lib 2.137.0
+ aws-cdk-lib 2.142.1
- cdk-nag 2.28.92
+ cdk-nag 2.28.119

devDependencies:
- npm-check-updates 16.14.18
+ npm-check-updates 16.14.20

Done in 4.7s
👾 upgrade | pnpm update @aws/pdk @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser constructs eslint-config-prettier eslint-import-resolver-typescript eslint-plugin-import eslint-plugin-prettier eslint npm-check-updates nx prettier projen syncpack ts-node typescript @aws-cdk/aws-cognito-identitypool-alpha aws-cdk-lib cdk-nag
Progress: removed

dependencies:
- @aws-cdk/aws-cognito-identitypool-alpha 2.134.0-alpha.0
+ @aws-cdk/aws-cognito-identitypool-alpha 2.142.1-alpha.0

devDependencies:
- @aws/pdk 0.23.35
+ @aws/pdk 0.23.38
- @types/node 18.19.26
+ @types/node 18.19.33 (20.12.12 is available)
- syncpack 12.3.0
+ syncpack 12.3.2

Done in 2.2s
👾 upgrade | pnpm exec projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 Installing dependencies...
👾 install | pnpm i --no-frozen-lockfile
Scope: all 3 workspace projects
Progress: removed

devDependencies:
- @aws/pdk 0.23.38
+ @aws/pdk 0.23.35 (0.23.38 is available)

Done in 4.4s
```

2. `projen` goes from `0.79.24` to `0.81.15` back to `0.79.27`

```bash

> @demo/monorepo@0.0.0 upgrade-deps UpgradeDemo
> pnpm exec projen upgrade-deps

👾 upgrade-deps | pnpm exec nx run-many --target=upgrade --output-style=stream --nx-bail --projects=@demo/api,@demo/api-model

 >  NX   The following projects do not have a configuration for any of the provided targets ("upgrade")

   - @demo/api
   - @demo/api-model

 >  NX   No projects with target upgrade for 0 projects were run

 >  NX   Successfully ran target upgrade for 0 projects


👾 upgrade-deps | pnpm exec npm-check-updates --deep --rejectVersion 0.0.0 -u --dep prod,dev,peer,optional,bundle --target=minor
Using pnpm
Upgrading UpgradeDemo/package.json
[====================] 20/20 100%

 constructs   ^10.0.0  →   ^10.3.0
 projen      ^0.79.24  →  ^0.81.15
Upgrading UpgradeDemo/packages/api/generated/infrastructure/typescript/package.json
[====================] 8/8 100%

 @aws/pdk     ^0.23.35  →   ^0.23.38
 aws-cdk-lib  ^2.137.0  →   ^2.142.1
 cdk-nag      ^2.28.92  →  ^2.28.119
 projen       ^0.79.24  →   ^0.81.15
Upgrading UpgradeDemo/packages/api/generated/runtime/typescript/package.json
[====================] 8/8 100%

 constructs   ^10.0.0  →   ^10.3.0
 projen      ^0.79.24  →  ^0.81.15

Run pnpm install to install new versions.
👾 upgrade-deps | pnpm exec syncpack fix-mismatches
= Default Version Group ========================================================
    18 ✓ already valid
    30 ✓ fixed
✓ package.json
✓ packages/api/generated/infrastructure/typescript/package.json
✓ packages/api/generated/runtime/typescript/package.json
👾 upgrade-deps | rm pnpm-lock.yaml
👾 upgrade-deps | pnpm i
Scope: all 3 workspace projects
 WARN  5 deprecated subdependencies found: @npmcli/move-file@2.0.1, are-we-there-yet@3.0.1, gauge@4.0.4, npmlog@6.0.2, read-package-json@6.0.4
Packages: +4 -25
++++-------------------------
Progress: resolved 637, reused 629, downloaded 0, added 0, done

devDependencies:
- @aws/pdk 0.23.35
+ @aws/pdk 0.23.38
- projen 0.79.27
+ projen 0.81.15

 WARN  Issues with peer dependencies found
.
└─┬ @aws/pdk 0.23.38
  └── ✕ unmet peer projen@^0.79.24: found 0.81.15

packages/api/generated/infrastructure/typescript
└─┬ @aws/pdk 0.23.38
  └── ✕ unmet peer projen@^0.79.24: found 0.81.15

Done in 6s
👾 upgrade-deps | pnpm exec projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 Installing dependencies...
👾 install | pnpm i --no-frozen-lockfile
Scope: all 3 workspace projects
 WARN  5 deprecated subdependencies found: @npmcli/move-file@2.0.1, are-we-there-yet@3.0.1, gauge@4.0.4, npmlog@6.0.2, read-package-json@6.0.4
Packages: +3 -2
+++--
Progress: resolved 637, reused 629, downloaded 0, added 0, done

devDependencies:
- projen 0.81.15
+ projen 0.79.27 (0.81.15 is available)

Done in 3.7s
```

3. Re-synthing projen seems irrelevant, dependencies are not updated.

### Reproduction Steps

Using these versions: `@aws/pdk 0.23.35` & `projen 0.79.24`

Running the following steps does not upgrade pdk/projen:

1. `pnpm run upgrade`
2. `pnpm upgrade-deps`
3. `pnpm default`

### Possible Solution

_No response_

### Additional Information/Context

A demo repo has been setup, hopefully it behaves the same in other environments:

https://github.com/raurir/projen-pdk-upgrade-issue/

### PDK version used

0.23.35

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Macos 14.4

### PR DESCRIPTION
**Pull request by agdimech**
Previously we were checking if a `License` existing on a project, if not we would add a default license specified via the monorepo's `licenseOptions`. This doesn't work however if a user has added a license manually. To resolve this, we now clobber any existing licenses that are found which should have been the desired behaviour in the initial implementation. If a user does not wish to do this, they simply need to opt out of the monorepo licensing by passing in the following:

```
licenseOptions: {
   disableDefaultLicenses: true
}
```

Fixes #784

### CODE REVIEW

File: packages/monorepo/src/components/nx-configurator.ts [hunk 1]
```diff
@@ -537,12 +537,9 @@ export class NxConfigurator extends Component implements INxProjectCore {
...
   private _addLicenses() {
     [this.project, ...this.project.subprojects]
-      .filter(
-        (p) =>
-          !this.licenseOptions?.disableDefaultLicenses &&
-          p.components.find((c) => c instanceof License) === undefined
-      )
+      .filter(() => !this.licenseOptions?.disableDefaultLicenses)
       .forEach((p) => {
+        p.tryRemoveFile("LICENSE");
```
Comment (martenpayne) [inline packages/monorepo/src/components/nx-configurator.ts:542]: I don't think you need to consider case variations (like "License" or "license"), but GitHub license files can be LICENSE or LICENSE.md

Comment (agdimech) [reply packages/monorepo/src/components/nx-configurator.ts:542]: Not necessary as we are only dealing with LICENSE files here.

**Review by martenpayne — APPROVED** [review]
looks good
